apiVersion: v1
kind: Pod
metadata:
  labels:
    app: minio
  name: minio
spec:
  containers:
  - name: minio
    image: docker.yektanet.tech/minio/minio:latest
    command:
    - /bin/bash
    - -c
    args: 
    - mkdir /data/test && minio server /data --console-address :9090
    volumeMounts:
    - mountPath: /data
      name: localvolume # Corresponds to the `spec.volumes` Persistent Volume
    env:
    - name: MINIO_ACCESS_KEY
      value: access
    - name: MINIO_SECRET_KEY
      value: secretsecret
  imagePullSecrets:
  - name: docker.yektanet.tech
  volumes:
  - name: localvolume
    hostPath: # MinIO generally recommends using locally-attached volumes
      path: /mnt/disk1/data # Specify a path to a local drive or volume on the Kubernetes worker node
      type: DirectoryOrCreate # The path to the last directory must exist
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  ports:
  - name: minio
    port: 9000
  selector:
    app: minio
