apiVersion: backup.yektanet.tech/v1
kind: RedisBackup
metadata:
  name: redisbackup-sample
spec:
  image: tparsa/redis-backup-aws:0.2.1
  uriSecretName: test-uri-secret
  awsConfigSecretName: test-aws-secret
  s3EndpointUrl: http://minio:9000
  bucket: test
  redisType: single
  db: 0
  retentionSpec:
    keepLast: 2
---
apiVersion: v1
kind: Secret
metadata:
  name: test-uri-secret
stringData:
  REDIS_URI: redis://redis:6379/0
---
apiVersion: v1
kind: Secret
metadata:
  name: test-aws-secret
stringData:
  AWS_ACCESS_KEY_ID: access
  AWS_SECRET_ACCESS_KEY: secretsecret
