{{- if .Values.rbac.install -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "name" . }}
  labels:
    {{- include "redis-backup-operator.labels" . | nindent 4 }}
imagePullSecrets:
{{ toYaml .Values.rbac.imagePullSecrets | indent 2 }}
{{- end }}
