# permissions for end users to edit redisbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redisbackup-editor-role
rules:
- apiGroups:
  - backup.yektanet.tech
  resources:
  - redisbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backup.yektanet.tech
  resources:
  - redisbackups/status
  verbs:
  - get
