# permissions for end users to view redisbackupschedules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redisbackupschedule-viewer-role
rules:
- apiGroups:
  - backup.yektanet.tech
  resources:
  - redisbackupschedules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - backup.yektanet.tech
  resources:
  - redisbackupschedules/status
  verbs:
  - get
