apiVersion: backup.yektanet.tech/v1
kind: RedisBackupSchedule
metadata:
  name: redisbackupschedule-sample
spec:
  image: tparsa/redis-backup-aws:0.1.2
  uriSecretName: test-uri-secret
  awsConfigSecretName: test-aws-secret
  s3EndpointUrl: https://kise-thr-nd-1.sotoon.cloud 
  bucket: yektanet-test
  redisType: single
  db: 0
  schedule: "* * * * *"